databases:
  - name: railsllm-postgresql
    databaseName: railsllm
    user: railsllm

services:
  - type: web
    name: railsllm
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: railsllm-postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString

  - type: redis
    name: cache
    ipAllowList: [] # only allow internal connections
    plan: free # or choose appropriate plan